name: Trigger EP-Pokeball Workflow

on:
  push:
    branches: 
        - pr/EP-50381/gha-ui

jobs:
  trigger-another-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Worklfow in EP-Pokeball Repo
        uses: actions/github-script@v6
        with:
            script: |
               const res = await github.rest.actions.createWorkflowDispatch({
                  owner: 'netskope',
                  repo: 'netskope/ep-pokeball',
                  workflow_id: 'docker-ui-push.yml',
                  ref: 'pr/EP-50381/gha',
               });
               console.log(res);
        env:
          GITHUB_TOKEN: ${{secrets.BOT_TOKEN}}
 