name: Trigger EP-Pokeball Workflow

on:
  push:
    branches: 
        - pr/EP-50381/gha-ui

jobs:
  trigger-another-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Worklfow in EP-Pokeball Repo
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.TEST_BOT_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/netSkope/ep-pokeball/actions/workflows/docker-ui-push.yml/dispatches \
          -d '{"ref":"pr/EP-50381/gha-2"}'
    
